### ISSUE TITLE
add more information about the base image

### ISSUE THREAD

**Issue by docwhat** [ibm-cloud-docs/ContinuousDelivery#19]
In the section "Working with versioned base images" it should include:

1. A link to the github repository that has the source for the "base image".
1. The URI to the base image.

In a separate section it should have instructions for testing a build on a local workstation; either for debugging or development of builds.

**Comment by acolleen** [comment]
Thank you for your feedback. We've updated the help based on your comments:
https://cloud.ibm.com/docs/services/ContinuousDelivery?topic=ContinuousDelivery-pipeline_versioned_base_images#image_version_contents
