### ISSUE TITLE
"{:codeblock}" rendering on 'Publishing test data to DevOps Insights'

### ISSUE THREAD

**Issue by maxwelldb** [ibm-cloud-docs/ContinuousDelivery#21]
Where: https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-publishing-test-data#upload-vulnerability-advisor

What: See screenshot. 

![image](https://user-images.githubusercontent.com/50179998/80144358-57945800-857c-11ea-8203-f5d97e19aa08.png)

**Comment by acolleen** [comment]
Hi Max, thanks for your feedback. I've fixed the issue that you reported:
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-publishing-test-data&locale=en#upload-vulnerability-advisor

**Comment by maxwelldb** [comment]
Thanks! LGTM.
