### ISSUE TITLE
Continuous Delivery failed to enable

### ISSUE THREAD

**Issue by faderrblak** [ibm-cloud-docs/ContinuousDelivery#22]
Created a Node.js application following a tutorial, my 2nd. The first one went smoothly. This one, however, I can't seem to enable the CD Toolchain. 
![Screenshot 2020-04-29 at 13 49 23](https://user-images.githubusercontent.com/42776617/80588258-b0526d80-8a20-11ea-8080-31ae38a60cfd.png)
![Screenshot 2020-04-29 at 13 49 37](https://user-images.githubusercontent.com/42776617/80588261-b2b4c780-8a20-11ea-9da8-296df969fd6c.png)

**Comment by acolleen** [comment]
Hello, you can find instructions about how to reach out for help from the IBM Cloud Continuous Delivery team here:

https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-cd_support&locale=en

They actively monitor our Slack channel and IBM Developer Answers for questions about the Continuous Delivery service and toolchains.
