### ISSUE TITLE
Both example pipelines fail 

### ISSUE THREAD

**Issue by tbrodbeck** [ibm-cloud-docs/ContinuousDelivery#23]
![Screenshot 2020-06-05 at 15 18 09](https://user-images.githubusercontent.com/24418160/83880672-c77f2c00-a73f-11ea-89be-7e4f24370ba6.png)
![Screenshot 2020-06-05 at 15 19 46](https://user-images.githubusercontent.com/24418160/83880793-ff866f00-a73f-11ea-986e-ed2b7283418f.png)

**Comment by acolleen** [comment]
Closing since these screen captures are not part of the Continuous Delivery documentation that this issue was opened against.

**Comment by tbrodbeck** [comment]
Ok as you wish, I am just trying to help... But trust me they are from this documentation

**Comment by acolleen** [comment]
Thank you for your feedback. Please provide a direct link to the documentation where you are seeing these screen captures. I was unable to locate them in the current Continuous Delivery documentation. Thanks for your assistance.

**Comment by tbrodbeck** [comment]
Ok, I did not know that you could not see the page from where I opened the issue.
I was trying to build the two examples when clicking the two button examples of https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-deploy-button

**Comment by acolleen** [comment]
Thanks for the clarification and details. I've reached out to the development team with the information you provided and they are investigating the issue that you reported with the sample pipelines failing.
