### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by drraghavendra** [ibm-cloud-docs/ContinuousDelivery#25]
Sign-in using cas3 auth failed
Sign-in failed because Email has already been taken.

Try logging in using your username or email. If you have forgotten your password, try recovering it

**Comment by acolleen** [comment]
@drraghavendra can you please provide a link to the help topic that you are submitting this feedback for so that I can investigate. Thanks!

**Comment by drraghavendra** [comment]
https://eu-gb.git.cloud.ibm.com/users/auth/cas3/omniauth_error?error=Email+has+already+been+taken

**Comment by acolleen** [comment]
Can you please provide the username that you are using to try to sign in?

**Comment by drraghavendra** [comment]
drraghavendra99@gmail.com

**Comment by ylu36** [comment]
Hi @drraghavendra . Does your account have another email address associated?

**Comment by drraghavendra** [comment]
yes,raghavendra@affineglobal.co.uk

**Comment by ylu36** [comment]
hi @drraghavendra . Please try signing with that email address. The gmail account is registered as the secondary email and cannot be used for sign in. Or, if you prefer, we can switch your two emails so you can sign in with gmail account

**Comment by acolleen** [comment]
@drraghavendra can you please let us know whether the suggestion from @ylu36 solved your issue? Thanks!

**Comment by drraghavendra** [comment]
Let me remind you for mail raghavendra@affineglobal.co.uk  associated  Resource groups and Toolchains are not available and visible.Due to above mentioned  issue,So I request your recommended act upon last and latest query

**Comment by ylu36** [comment]
@drraghavendra you should be able to sign in with the gmail account, and the other email is your secondary email now. Let us know if there is any other concern

**Comment by Apollo9999** [comment]
Please make a note as resource groups and Toolchains are not reflected in my IBM cloud which are essential for competition callforcode submission.

**Comment by drraghavendra** [comment]
Please make a note as my mail raghavendra@affineglobal.co.uk resource groups and toolchains are not available and visible in my login  which forms the crux and core  for code submission of IBM callforcode under covid19 category.

**Comment by drraghavendra** [comment]
Thanks a lot issue resolved.
