### ISSUE TITLE
Would be nice to make the slack integration less "talkative"

### ISSUE THREAD

**Issue by jb-dk** [ibm-cloud-docs/ContinuousDelivery#26]
If you have a pipeline with 3 stages, and some of the stages has 5 jobs, this integration to slack becomes rather noisy.
WOuld be nice to simply configure granularity.
1. Tell about all jobs
2. Tell about all stages
3. Tell about pipeline start and stop

In all cases in case of failure, let the last "started" also tell it failed. But do not tell about all jobs if this is not what the user wants - it can be rather noise as it is right now :-)

**Comment by acolleen** [comment]
Closing based on the resolution from this Slack discussion thread:
https://ibm-cloudplatform.slack.com/archives/C066S82GY/p1602076040136700?thread_ts=1602060314.126000&cid=C066S82GY
