### ISSUE TITLE
Create toolchain has incorrect link

### ISSUE THREAD

**Issue by mfuse** [ibm-cloud-docs/ContinuousDelivery#29]
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-tutorial-cd-kube-image-signing

Step 2 on the doc, clicking **Create toolchain** will create a toolchain with template key-management-admin-toolchain.
It doesn't make sense. It's a prerequisite template.

In the Step 3, following is not generated task.

> cra-discovery-scan, code-vulnerability-scan, cra-cis-check, and cra-bom: These tasks are included in the Code Risk Analyzer capability within Continuous Delivery. Use Code Risk Analyzer to discover vulnerabilities in your Python, Node.js, and Java® applications, and in your operating system stacks (base image). Code Risk Analyzer uses rich threat intelligence from Snyk and Clair and then provides fix recommendations. Code Risk Analyzer also integrates the comprehensive security coverage in Snyk to help you to automatically find, prioritize, and fix vulnerabilities in open source dependencies and containers early in your workflow. Complete the Code Analyzer tutorial to try using the Code Risk Analyzer.

**Comment by kqli** [comment]
https://github.ibm.com/org-ids/ua-issues/issues/1471
@mfuse this issue has been tracked here. Do you prefer to close this one and track it at issue 1474? thank you

**Comment by mfuse** [comment]
I see. closing this. Thanks
