### ISSUE TITLE
Update the link and title of the VSI Template in the Document

### ISSUE THREAD

**Issue by mundrapiyush36** [ibm-cloud-docs/ContinuousDelivery#30]
1. Update the link in the "Create Toolchain" Button below to:

![image](https://user-images.githubusercontent.com/80688956/117930027-1ef82580-b31b-11eb-91be-9ca978733be9.png)

- Existing: https://cloud.ibm.com/devops/create?env_id=ibm:yp:us-south
- Update: https://cloud.ibm.com/devops/setup/deploy?repository=https%3A%2F%2Fgithub.com%2Fopen-toolchain%2Fsimple-vsi-toolchain&topic=ContinuousDelivery-tutorial-cd-vsi&env_id=ibm:yp:us-south

2.  Update the references in below sections:

![image](https://user-images.githubusercontent.com/80688956/117930823-17854c00-b31c-11eb-857a-b374fb386a9d.png)

The title should match the one in the tile below:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/80688956/117931301-a6926400-b31c-11eb-97d8-6ee4bcd3215f.png">

- Existing: Develop a Java application and deploy to Virtual Server (Virtual Machine)
- Update: Develop an application for a Virtual Machine

3. Update the screenshot:

- Existing

<img width="778" alt="image" src="https://user-images.githubusercontent.com/80688956/117934083-e870d980-b31f-11eb-96f0-0f4cba558b87.png">

- Update

<img width="751" alt="image" src="https://user-images.githubusercontent.com/80688956/117934019-d131ec00-b31f-11eb-8a58-41c50227c9b0.png">

**Comment by acolleen** [comment]
@mundrapiyush36 please create this PR in the internal doc repo: https://github.ibm.com/cloud-docs/ContinuousDelivery Thanks!
