### ISSUE TITLE
Support for Hyper Protect Crypto Services and a Classic VSI 

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/ContinuousDelivery#31]
I tried to create a Toolchain and saw the following blockers:
- I want to use the HPCS (Hyper Protect Crypto Service) instance provisioned in my IBM Cloud Account to store my API Keys
- I want to use a Key I have in HPCS to sign my images
- I want the target VSI to be the one in Classic that I have provisioned in my IBM Cloud Account

How can I make that happen?

**Comment by acolleen** [comment]
@sandeep-at-ibm please post your question to the #devops-open-toolchain Slack channel for support. Thanks!
