### ISSUE TITLE
Under Continuous Delivery Artifact integration, add section for docker registry configuration

### ISSUE THREAD

**Issue by barvek** [ibm-cloud-docs/ContinuousDelivery#34]
Docker registration configuration using artifact is missing under Continuous delivery section of docs. Please add.

**Comment by acolleen** [comment]
@barvek thank you for your feedback. Can you please provide a link to the topic that you would like to be updated.

**Comment by barvek** [comment]
It's been really long since I visited these docs, so I might be wrong but I guess I was referring to this document: https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-deliverypipeline_about&interface=ui#artifacts

**Comment by SidneyJiang** [comment]
@barvek Could you provide more details about what are you looking for? it sounds like you are looking for doc about an extension build job type of classic pipeline, but I can't be sure which one. Could you provide some screenshot as well please?

**Comment by acolleen** [comment]
@SidneyJiang can you please provide status on this issue?

**Comment by SidneyJiang** [comment]
@barvek I think it is clearly enough already.  You just use a correct image URL of your registry, as documented:
```
For example, registry.hub.docker.com/library/maven:3.5.3-ibmjava.
```
then add DOCKER_USERNAME and DOCKER_PASSWORD env properties..

All seems clear to me.  

There's no magic bridge beween any Artifactory registry and pipeline.  All we need is just the image URL , DOCKER_USERNAME, DOCKER_PASSWORD.   What else is unclear?

**Comment by barvek** [comment]
@SidneyJiang : You can close this issue.
