### ISSUE TITLE
Doc enhancement - IBM_CLOUD_API_KEY

### ISSUE THREAD

**Issue by knobutan** [ibm-cloud-docs/ContinuousDelivery#41]
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-pipeline_container_images
This page should emphasise users to have an additional env var `IBM_CLOUD_API_KEY` for buildctl commands. They will only fill API key for authentication but you must set it for buildctl as well. Upon deprecation of `ibmcloud cr build` this part should be written clearly.

**Comment by acolleen** [comment]
The documentation has been updated:
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-pipeline_container_images
