### ISSUE TITLE
Do the templates use GitHub or Git Repos?

### ISSUE THREAD

**Issue by aaronralls** [ibm-cloud-docs/ContinuousDelivery#45]
The table mentions both types. Are certain templates tied to GitHub and others are not?

GitHub and Issues

Git Repos and Issue Tracking

**Comment by acolleen** [comment]
@aaronralls do you have a  pointer to the help topic that your question refers to?

**Comment by acolleen** [comment]
Closing since there has been no response from the feedback originator.
