### ISSUE TITLE
Please be more clear about the time format

### ISSUE THREAD

**Issue by IzhakJakov** [ibm-cloud-docs/ContinuousDelivery#50]
The document says:

- expiration - If this property is set to true and the expiration date is not reached, the vulnerability is omitted. If the expiration date is reached, the vulnerability is not omitted and a message is displayed

Then the example shows:
```json
[
    {
        "cve": "SNYK-BLA-BLA-BLA",
        "expiration": "2022-02-10T22:08:41+04:00",
        "comment": "Additional security measures are in place"
    }
]
```

This is ambiguous.
  
What time format are you using?
1. `yyyy-MM-dd'T'HH:mm:ss+Z`
2. `yyyy-dd-MM'T'HH:mm:ss[-+]Z`
3. `<something_else>`

Can you please clarify?

Thanks in advance.

**Comment by acolleen** [comment]
@IzhakJakov can you please provide the URL for the topic that your feedback applies to so we can look into this for you. Thank you!

**Comment by IzhakJakov** [comment]
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-cd-configure-cra-repos

**Comment by DavidLopezIBM** [comment]
@IzhakJakov Hi, sorry for the confusion. Will be creating a work item to add this information to the docs. The expiration field should follow RFC3339 format (yyyy-MM-dd'T'HH:mm:ss[+-]Z or if running in UTC then just yyyy-MM-dd'T'HH:mm:ss'Z') and the expiration time/date will be compared to the local time that is being ran against.

**Comment by IzhakJakov** [comment]
Thank you! That is useful information.

**Comment by acolleen** [comment]
The documentation is now updated with this information:
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-cd-configure-cra-repos#cra_omit_vulnerabilities
