### ISSUE TITLE
"Getting Started with Continuous Delivery" seems unhelpful

### ISSUE THREAD

**Issue by ThinkOpenly** [ibm-cloud-docs/ContinuousDelivery#53]
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-getting-started

I'd argue that this page doesn't actually talk about Continuous Delivery. It is mentioned in the Prerequisites, but never mentioned again. The steps following are for creating a toolchain.

**Comment by acolleen** [comment]
This topic has undergone several reviews and updates since this issue was created. Closing since the feedback in this issue has been addressed.
