### ISSUE TITLE
Tutorial Links Dead

### ISSUE THREAD

**Issue by daniel-butler-irl** [ibm-cloud-docs/ContinuousDelivery#55]
https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-di_working
All the tutorial links are dead

**Comment by acolleen** [comment]
Thank you for your feedback. It looks like the "alternative tutorials" that are linked to have been removed from the IBM Cloud Garage Method site and are no longer available. I've removed this section from the "Working with DevOps Insights" topic.
